spring:
  application:
    name: SWIGGY-API-GATEWAY
  config:
    import: configserver:http://localhost:9595
  cloud:
    gateway:
      routes:
        - id: swiggy-app
          uri: lb://SWIGGY-APP #load balancing
          predicates:
            - Path=/swiggy/**
          filters:
            - AuthenticationFilter #securing swiggy app

        - id: restaurant-service
          uri: lb://RESTAURANT-SERVICE
          predicates:
            - Path=/restaurant/**
          filters:
            - AuthenticationFilter #securing restaurant service

        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**




#eureka:
#  client:
#    service-url:
#      defaultZone : http://localhost:8761/eureka/